version: "3"
services:
    frontend:
        container_name: web
        build:
          context: ./client
          dockerfile: Dockerfile
        image: resume/web
        environment: 
          REACT_APP_NODE_PATH: "src"
        ports:
          - "80:3000"
        volumes:
          - ./client:/usr/src/app/
          - /usr/src/app/node_modules